apiVersion: v1
kind: Service
metadata:
  name: frontend-service-dev
spec:
  selector:
    app: frontend-dev
  ports:
    - protocol: TCP
    # outside port
      port: 3000
    # port exposed in the deployment
      targetPort: 80
  type: LoadBalancer
